In [12]:
#切片Slice练习
#python用切片简化常用的对元素的索引循环，可用于list，string，tuple

In [13]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]]) 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#从前往后切，省略第一个元素默认为0
y1= x[0][:2]
y1

array([1, 2])

In [18]:
#从后往前切，省略最后一个元素默认为-1
y2=x[0][-2:]
y2

array([2, 3])

In [16]:
#取到整个列表，相当于复制
y3=x[0][:]
y3

array([1, 2, 3])

In [17]:
#以整个列表为基准，并每隔2个元素取出来
y4=x[0][::2]
y4

array([1, 3])

In [19]:
#对二维数组的切片
z1=x[1:,0]
z1

array([4])

In [21]:
z2=x[1,-1:]
z2

array([6])

In [22]:
z3=x[:,:]
z3

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
z4=x[::2,::2]
z4

array([[1, 3]])